# Generated by Django 4.2.4 on 2023-09-14 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_alter_formation_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ids', models.CharField(max_length=200)),
                ('titre', models.CharField(max_length=200)),
                ('datee', models.CharField(max_length=200)),
                ('desciption', models.CharField(max_length=5000)),
                ('image', models.CharField(max_length=5000)),
                ('langage', models.CharField(max_length=500)),
            ],
        ),
    ]
