# Generated by Django 4.2.4 on 2023-09-14 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formation',
            name='image',
            field=models.CharField(max_length=5000),
        ),
    ]
