# Generated by Django 4.2.4 on 2023-10-02 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_projets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formation',
            name='ids',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='projets',
            name='ids',
            field=models.CharField(max_length=2000),
        ),
    ]
