# Generated by Django 4.2.4 on 2023-10-02 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_alter_formation_ids_alter_projets_ids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formation',
            name='address',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='formation',
            name='datee',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='formation',
            name='lieu',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='formation',
            name='titre',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='projets',
            name='datee',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='projets',
            name='langage',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='projets',
            name='titre',
            field=models.CharField(max_length=2000),
        ),
    ]
